Add nalgebra compatibility for DualVec
itt-ustutt/num-dual pull request #59
Opened 2023-04-21 10:32 UTC by cormacrelf

Does what it says on the tin. Partially addresses #55 

- Only implemented for DualVec, not the more complicated ones
- But this impl should serve pretty well as a model for the other types
- I am not 100% sure of the RealField and ComplexField impls. Can someone go over these and see if they make sense for dual numbers?
- Missing atan2 and copysign, panics instead, wasn't sure what to do about those. Is there a reference implementation of atan2 on duals?
- Bonus: prettier Display implementation like `0.35355338 + 2.404471ε`

The Simd-enabled part turned out to be useless for now, see https://github.com/dimforge/simba/issues/44. It was pretty easy to implement SimdValue and thus we are able to split a `DualVec<simba::simd::f32x4, f32, 1>` into four `DualVec<f32, f32, 1>`, and join them back together. This is for when you are implementing `SimdRealField`, but we are not able to implement that directly and thus use T's vectorized operations. So we are stuck with implementing the non-vectorized `RealField`/`ComplexField` for now. If that problem is fixed, we'll be able to swap out that with the Simd version of the trait, using basically find/replace `fn ` with `fn simd_` or thereabouts.

2023-04-21 16:03 UTC, cormacrelf commented
Here's an atan2 on hyper-duals at least

https://github.com/oberbichler/HyperJet/blob/main/include/hyperjet/hyperjet.h

2023-04-21 16:18 UTC, cormacrelf commented
Atan2 on duals https://github.com/LLNL/serac/blob/develop/src/serac/numerics/functional/dual.hpp#328

2023-04-21 17:13 UTC, prehner commented
Thank you for the very nice contribution! This should also enable us to switch from the custom implementation of eigenvalues to nalgebra. I will finish work on #58 which was basically only waiting for confirmation that downstream crates do not suffer from any performance loss. Afterwards, I would ask you to rebase this branch and I hope to have a closer look at this soon.

2023-04-22 12:00 UTC, tsmith023 commented
@cormacrelf, this is fantastic! I've been working on implementing this exact integration but yours is far superior to mine so I will cease development of my work and await this merge to achieve the functionality that I desire :grin: I feel your pain around the SimdValue issues as I spent a long time banging my head against that wall before resigning myself to the ComplexField way!

@prehner, do you envisage this crate ever extending beyond reals to complex? Or is this something that is beyond the scope of the package? (Since that would entail some form of quaternion algebra) I ask since the nalgebra integration here assumes, as it rightly should, that F is bound to Float such that the ComplexField has no imaginary part.

If I can help in anyway with regards to review or contribution then please let me know!

P.S. For the atan2 of duals, an implementation might look something like this:
```rust
fn atan2(self, other: Self) -> Self {
    let re = self.re.atan2(other.re);
    let dx = (self.re * other.eps.into()) / (self.re.powi(2) + other.re.powi(2)); 
    let dy = (other.re * self.eps.into()) / (self.re.powi(2) + other.re.powi(2));
    DualVec {
        re: re,
        eps: StaticVec::from(dy-dx),
        f: PhantomData, // Is this aspect correct?
    }
}
```

2023-04-23 09:25 UTC, prehner commented
With regards to extending to complex numbers: At the moment, I think I don't see where exactly the problem comes from, but that is likely due to me also giving up on the complexity of the nalgebra trait system. In theory you could have a dual number with complex numbers as elements (that would require the complex type to implement DualNum for most of the operations) or have a complex number with dual numbers as elements (Then the implementation of the complex number data type has to be generic enough to allow that). Mathematically that is the same.

With regards to atan2: Your suggested implementation looks good. The PhantomData can be hidden by simply calling the `new` constructor.

2023-04-23 23:03 UTC, cormacrelf commented
Yes. And for example the test I added in this PR uses a UnitQuaternion. Quaternions are complex numbers with three imaginary parts, but like the 2-dimensional complex numbers, all four parts are represented as reals. The imaginary bits are just coefficients . This crate's types are perfectly capable of emulating a real number for nalgebra by implementing the RealField or SimdRealField trait.

The confusion around this probably comes from simba/nalgebra's traits not having enough docs, ie RealField requiring ComplexField as well without really explaining why.

I note that the implementation of ComplexField for this crate follows the one for f32 and f64. There simply isn't a complex part. It returns zero when you ask and otherwise behaves as if there is no complex part (so norm1() == abs()). AFAICT The trait ComplexField does not map to a mathematical trait like "field" or "ring", it is merely a way to make stuff like "multiplying a `Complex<f32>` by an f32" a bit faster since you don't need to upgrade the f32 first, it already knows how to present itself as a complex number.

It's certainly possible that nobody has wanted to implement these traits enough to warrant documenting them. Certainly the issue I linked makes it seem that way, as you would think someone would have found it before. Since I have wrapped my head around it, I should probably send some docs PRs to simba.

2023-04-30 16:37 UTC, prehner commented
Division is only a problem if the real part is zero, which comes at no surprise. Some methods, like the norm, might have different meanings/results for a `Dual<Complex<f64>>` and a `Complex<Dual<f64>>` but I don't see that as a big problem. After all, in practice that would depend on what the actual application is. Now that I think about it, we actually use `Complex<T>` with `T: DualNum<f64>` in some part of our code. Both the real and imaginary parts of the complex number then depend on some input variable and the dual parts of each contain the derivatives with respect to that variable.

@cormacrelf Can you rebase this PR on the current master?

2023-05-02 15:30 UTC, cormacrelf commented
Yep, just took a lot of wrangling and I've been busy with other things. Everything needed truly awful amounts of `DefaultAllocator` trait bounds (more than you would think!) and the move to the Derivative with an Option in it was painful. But it worked out.

2023-05-02 15:56 UTC, tsmith023 commented
Looking forward to having this functionality merged, thanks again both!

2023-05-07 08:17 UTC, prehner requested changes
Thank you for the patience. The rebase and the introduction of the `Derivative` struct goes indeed quite against the SIMD implementation. After all it was done to allow for dynamically sized dual numbers which are probably not optimal for SIMD. However, as you write this is mostly about unlocking nalgebra functionalities that are hidden behind these traits and not actually optimizing dual numbers with SIMD.

Going through this PR really reinforced my suspicion that nalgebra has design flaws when it comes to trait bounds and the usage of data types aside from f32 and f64. But how are the chances that they tighten it up when that is not the main focus of the crate?

2023-05-07 08:17 UTC, prehner commented on src/dual.rs
> +        }
For readability, I suggest using the new constructor in these places instead.

2023-05-07 08:17 UTC, prehner commented on src/derivative.rs
>  use nalgebra::*;
clippy has some suggestions in this file that you might want to consider.

2023-05-08 18:12 UTC, merged